version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server-container
    ports:
      - '5000:5000'
    networks:
      - mynetwork
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - '80:80'
    networks:
      - mynetwork
    environment:
      - NODE_ENV=production
    depends_on:
      - server
    restart: unless-stopped

networks:
  mynetwork:
    driver: bridge